### PR TITLE
Adding Fish and Zsh alternative shells

### PR DESCRIPTION
**Pull request by bap14**
Adds Zsh and Fish shells (and composer and git completions for Zsh).

This would only work for php images (where you're most likely to use the shell).

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
Just wonder how much images becoming bigger

**Comment by bap14** [comment]
@ihor-sviziev In looking at the layer that specifically adds the shells...

<table>
<tr><th>Image ID</th><th>Last Built</th><th>Command</th><th>Size</th></tr>
<tr><td>Den PHP-FPM 8.1<br />80c35f1c8f94</td><td>4 days ago<td><code>RUN /bin/sh -c apk --no-cache add jq bash patch pv procps nano vim mariadb-client sudo busybox-initscripts gettext ca-certificates shadow git rsync bash-completion # buildkit</code></td><td>84.2MB</td></tr>
<tr><td>Den PHP-FPM 8.1<br />with Shells</td><td>14 hours ago<td><code>RUN /bin/sh -c apk --no-cache add     jq     bash     patch     pv     procps     nano     vim     mariadb-client     sudo     busybox-initscripts     gettext     ca-certificates     shadow     git     rsync     bash-completion     fish     zsh     composer-zsh-completion     git-zsh-completion # buildkit</code></td><td>97.3MB</td></tr>
<tfoot>
<tr><td colspan="2"></td><td align="right">Size Difference</td><th>13.1MB</th><tr>
</tfoot>
</table>

It's not a huge amount, but it's enough to add a second or two to download times initially.

**Comment by navarr** [comment]
The point of using Alpine was definitely to be smaller. I'm not sure if the size outweighs the perceived benefits right now. 

I do wonder what the "right way" should be. For an alternative shell, I'm kind of leaning towards a Dockerfile that extends Den but adds the shells using `.warden`

My other concern is whether or not n98 completion can be made to work with the alternate shells. Very minor concern, but still a question

**Comment by bap14** [comment]
@navarr Looks like n98 has Fish and Zsh compatibility: https://github.com/netz98/n98-magerun2/tree/develop/res/autocompletion ; however, it's old and needs some work. I did some work to add those completions and make them compatible. I don't really use n98-magerun so I just made sure typing an alias, then hitting tab a couple of times would provide the list of commands:

Fish shell:
image

Zsh shell:
image

**Comment by bap14** [comment]
@navarr As for the size issue, I don't think ~15MB is going to hurt much. I would still argue that the "correct" way to solve this is for those that want alternative shells to be just build their own off of our images (using what I've got as a starting point) and just maintaining their own forks of the base Den images.

I'm neither for this, nor against it. This was just work I wanted to put forth in case more people came out in favor of alternative shells.

**Comment by sprankhub** [comment]
Thank you so much for putting the work into this! I am biased, but I would indeed not care about the 15 MB given the advantage of having multiple shells OOTB. But it is really up to you, because you guys maintain that project :)

**Comment by DavidLambauer** [comment]
Agree to @sprankhub ! This is such a great feature!

**Review by navarr — APPROVED** [review]

**Pull request merged**
