### PR TITLE
Update PHP Node dockerfile

### PR DESCRIPTION
**Pull request by bap14**
Fix failing builds for older alpine versions

### CODE REVIEW

**Comment by bap14** [comment]
Failing due to invalid credentials.

**Comment by navarr** [comment]
apk del is throwing error code 130

```
navarr@Navarrs-MacBook-Pro-2 php-fpm % docker build -f node/Dockerfile context --build-arg ENV_SOURCE_IMAGE=ghcr.io/swiftotter/den-php-fpm --build-arg NODE_VERSION=12 --build-arg PHP_VERSION=7.0 
[+] Building 4.0s (15/15) FINISHED                                                                                                                                                                                                                                                                                    
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                                                             0.0s
 => => transferring dockerfile: 1.00kB                                                                                                                                                                                                                                                                           0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                                                0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                                                  0.0s
 => [internal] load metadata for ghcr.io/swiftotter/den-php-fpm:7.0                                                                                                                                                                                                                                              0.0s
 => [internal] load metadata for docker.io/library/node:12-alpine                                                                                                                                                                                                                                                1.3s
 => [auth] library/node:pull token for registry-1.docker.io                                                                                                                                                                                                                                                      0.0s
 => CACHED [stage-1 1/8] FROM ghcr.io/swiftotter/den-php-fpm:7.0                                                                                                                                                                                                                                                 0.0s
 => [node 1/2] FROM docker.io/library/node:12-alpine@sha256:d4b15b3d48f42059a15bd659be60afe21762aae9d6cbea6f124440895c27db68                                                                                                                                                                                     0.0s
 => CACHED [node 2/2] RUN npm install -g grunt-cli gulp                                                                                                                                                                                                                                                          0.0s
 => [stage-1 2/8] COPY --from=node /usr/lib /usr/lib                                                                                                                                                                                                                                                             0.1s
 => [stage-1 3/8] COPY --from=node /usr/local/share /usr/local/share                                                                                                                                                                                                                                             0.0s
 => [stage-1 4/8] COPY --from=node /usr/local/lib /usr/local/lib                                                                                                                                                                                                                                                 1.4s
 => [stage-1 5/8] COPY --from=node /usr/local/include /usr/local/include                                                                                                                                                                                                                                         0.1s
 => [stage-1 6/8] COPY --from=node /usr/local/bin /usr/local/bin                                                                                                                                                                                                                                                 0.2s
 => [stage-1 7/8] COPY --from=node /opt /opt                                                                                                                                                                                                                                                                     0.0s
 => ERROR [stage-1 8/8] RUN PACKAGES="ghostscript imagemagick gcc x265-libs libheif mariadb-client fish icu-libs libde265 libstdc++"     && VERS=$(cat /etc/*-release | grep -i '^[0-9.]\+$')     && COMPARISON=$(apk version -t "$VERS" "3.16")     && ( [[ "$COMPARISON" = ">" || "$COMPARISON" = "=" ]] && P  0.3s
------
 > [stage-1 8/8] RUN PACKAGES="ghostscript imagemagick gcc x265-libs libheif mariadb-client fish icu-libs libde265 libstdc++"     && VERS=$(cat /etc/*-release | grep -i '^[0-9.]\+$')     && COMPARISON=$(apk version -t "$VERS" "3.16")     && ( [[ "$COMPARISON" = ">" || "$COMPARISON" = "=" ]] && PACKAGES="${PACKAGES} libjxl" )     ; apk del $PACKAGES && apk add --update --no-cache $PACKAGES:
#15 0.298 WARNING: Ignoring APKINDEX.70c88391.tar.gz: No such file or directory
#15 0.298 WARNING: Ignoring APKINDEX.5022a8a2.tar.gz: No such file or directory
------
executor failed running [/bin/sh -c PACKAGES="ghostscript imagemagick gcc x265-libs libheif mariadb-client fish icu-libs libde265 libstdc++"     && VERS=$(cat /etc/*-release | grep -i '^[0-9.]\+$')     && COMPARISON=$(apk version -t "$VERS" "3.16")     && ( [[ "$COMPARISON" = ">" || "$COMPARISON" = "=" ]] && PACKAGES="${PACKAGES} libjxl" )     ; apk del $PACKAGES && apk add --update --no-cache $PACKAGES]: exit code: 3
```

Everything _looks_ fine, so I'm not sure why its happening

**Comment by navarr** [comment]
@bap14 Feel free to ignore the checks, they've... never worked and I think they might actually push even though they shouldn't.  I'll be removing them

**Comment by bap14** [comment]
@navarr Not sure why `apk del` is failing, but I tested using 7.3 and 7.4 (as that was the difference in alpine from 3.15 to 3.16). I can go back and check PHP 7.0 and see why it's failing and see if there's an easy solution.

**Comment by bap14** [comment]
@navarr Another question is: At what point should we stop building the old EOL'ed versions of PHP? They're not changing, so I don't think there's any real benefit to rebuilding the images daily.

**Comment by navarr** [comment]
Unless we change the approach for bringing on node, the one benefit to rebuilding the old PHP images is new node versions.  We could theoretically do them ad-hoc.

Generally, I wouldn't want to support EOL versions at all.

**Comment by bap14** [comment]
@navarr  The build for PHP 7.0 was failing because packages were to be removed/added were not found in the Alpine package repository. The offending packages were:

- libheif
- libde265
- x265-libs

I'm haven't looked at when/why these were added, but `libheif` and `libde265` weren't included in the Alpine package repository until Alpine 3.10, and `x265-libs` was available starting with Alpine 3.9.

So the current solution is to add an ugly "if" condition that will add these packages if they're available. It's not great, but it does build PHP 7.0, 7.1, 7.2, 7.3 and 7.4.

**Pull request closed without merging**
